name: 'iOS Simulator UDID Action'
description: 'Custom GitHub Action to retrieve the iOS Simulator UDID.'

inputs:
  os_version:
    description: 'iOS version to use for the simulator runtime (e.g., 17-5)'
    required: false
    default: '17-5'  # Default OS version

runs:
  using: 'composite'
  steps:
    - name: Install Xcode command-line tools
      run: xcode-select --install > /dev/null 2>&1 || true
      shell: bash

    - name: Set Xcode version
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer > /dev/null 2>&1
      shell: bash

    - name: Start iOS Simulator and output UDID
      run: |
        OS_VERSION=${{ inputs.os_version }}
        echo "Creating iOS Simulator with runtime: iOS-$OS_VERSION"
        DEVICE_UDID=$(xcrun simctl create "iPhone-13" com.apple.CoreSimulator.SimDeviceType.iPhone-13 com.apple.CoreSimulator.SimRuntime.iOS-$OS_VERSION)
        xcrun simctl boot $DEVICE_UDID > /dev/null 2>&1
        echo $DEVICE_UDID > udid.txt
      shell: bash