name: 'iOS Simulator UDID Action'
description: 'Custom GitHub Action to retrieve the iOS Simulator UDID.'

inputs:
  os_version:
    description: |
      iOS version to use for the simulator runtime. Specify the version in the format "major-minor" (e.g., "17.0", "17.2", "17.4", "17.5").
    required: false
    default: '17.5'

  iphone_type:
    description: "iPhone model to use for the simulator (e.g., iPhone 15, iPhone 14)."
    required: false
    default: 'iPhone 15'

runs:
  using: 'composite'
  steps:
    - name: Install Xcode Command-Line Tools
      run: |
        echo "Checking for Xcode command-line tools..."
        if ! xcode-select --version &> /dev/null; then
          echo "Installing Xcode command-line tools..."
          xcode-select --install
        else
          echo "Xcode command-line tools already installed."
        fi
      shell: bash

    - name: Set Xcode Version
      run: |
        echo "Setting Xcode version..."
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
      shell: bash

    - name: List Available Simulators (Before Creating)
      run: xcrun simctl list devices
      shell: bash

    - name: Find Existing Simulator
      run: |
        # # Set simulator parameters and export them to the environment
        # echo "DEVICE_NAME=${{ inputs.iphone_type }}" >> $GITHUB_ENV
        # echo "OS_VERSION=${{ inputs.os_version }}" >> $GITHUB_ENV
        
        # # Load the environment variables
        # DEVICE_NAME=${{ inputs.iphone_type }}
        # OS_VERSION=${{ inputs.os_version }}
        # echo "Searching for an available simulator: $DEVICE_NAME..."
        
        # DEVICE_UDID=$(xcrun simctl list devices | \
        #   sed -n "/$OS_VERSION/,/^$/p" | \
        #   grep -E "$DEVICE_NAME \(" | \
        #   grep -oE '[A-Fa-f0-9-]{36}' | \
        #   head -n 1 | tr -d '\n')
        
        # if [[ -z "$DEVICE_UDID" ]]; then
        #   echo "ERROR: No available simulator found for $DEVICE_NAME"
        #   exit 1
        # fi
        # Set simulator parameters and export them to the environment
        echo "DEVICE_NAME=iPhone 15" >> $GITHUB_ENV
        echo "OS_VERSION=17.5" >> $GITHUB_ENV
        
        # Load the environment variables
        DEVICE_NAME="iPhone 15"
        OS_VERSION="17.5"
        
        echo "Searching for an available simulator: $DEVICE_NAME..."
        
        # Extract the UDID by filtering the list output
        DEVICE_UDID=$(xcrun simctl list devices | \
        sed -n "/$OS_VERSION/,/^$/p" | \
        grep -E "$DEVICE_NAME \(" | \
        grep -oE '[A-Fa-f0-9-]{36}' | \
        head -n 1 | tr -d '\n')

        echo "Using existing simulator: $DEVICE_UDID"
        
        # Boot the found simulator
        echo "Booting simulator $DEVICE_UDID..."
        xcrun simctl boot "$DEVICE_UDID"

        # Store UDID for later steps
        echo "DEVICE_UDID=$DEVICE_UDID" >> $GITHUB_ENV
      shell: bash
      
    - name: Wait for Simulator to Boot
      run: |
        DEVICE_UDID="${{ env.DEVICE_UDID }}"
        echo "Waiting for simulator ($DEVICE_UDID) to boot..."
        
        while ! xcrun simctl list devices | grep "$DEVICE_UDID" | grep -q "Booted"; do
          echo "Still waiting for the simulator to boot..."
          sleep 5
        done
        
        echo "Simulator $DEVICE_UDID is now fully booted!"
      shell: bash

    - name: Verify Simulator is Running
      run: xcrun simctl list devices | grep "Booted"
      shell: bash
